spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product-service?serverTimezone=UTC
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # or your preferred mode (update, create, validate, none)
    database-platform: org.hibernate.dialect.PostgreSQLDialect
